server:
  port: 8762
spring:
  application:
    name: merchant
  datasource:
    url: jdbc:mysql://localhost:3306/month6_1812
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      mr: debug